### ISSUE TITLE
Error when creating WMI service sensor c#

### ISSUE THREAD

**Issue by JamesDolphin** [lordmilko/PrtgAPI#248]
I am receiving the following error when attempting to create a WMI Service sensor.

```
{"ClassName":"System.InvalidOperationException","Message":"Property 'Services' requires a value, however an empty collection was specified.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"
   at PrtgAPI.Request.RequestParser.ValidateRequiredValue(PropertyInfo property, NewObjectParameters parameters, DependentPropertyAttribute attrib)
   at PrtgAPI.Request.RequestParser.ValidateObjectParameters(NewObjectParameters parameters)
   at PrtgAPI.PrtgClient.AddObjectInternal(Either`2 parent, NewObjectParameters parameters, CancellationToken token)
   at PrtgAPI.PrtgClient.<>c__DisplayClass151_0`1.<AddObject>b__0(CancellationToken t)
   at PrtgAPI.PrtgClient.ResolveWithDiff[T](Action`1 createObject, Func`2 getObjects, Func`3 exceptFunc, CancellationToken token, Action`2 errorCallback, Func`1 shouldStop, Boolean allowMultiple, String enhancedResolutionError)
   at PrtgAPI.PrtgClient.AddObject[T](Either`2 parent, NewObjectParameters parameters, Func`3 getObjects, Boolean resolve, CancellationToken token, Action`2 errorCallback, Func`1 shouldStop, Boolean allowMultiple)
   at PrtgAPI.PrtgClient.AddSensor(Either`2 deviceOrId, NewSensorParameters parameters, Boolean resolve, CancellationToken token)
   at Olinqua.PRTG.Configurator.Configurator.CreateGroup(PrtgClient client, PrtgGroup incomingGroup, PrtgGroup parentGroup)
```

Following the written example provided here: https://github.com/lordmilko/PrtgAPI/wiki/Sensor-Targets#supported-types

Code being run 

```c#
var serviceTarget = client.Targets.GetWmiServices(madeDevice).Where(s => s.Name.Contains(sensor.ServiceName)).ToList().FirstOrDefault();

var parameters = new WmiServiceSensorParameters(serviceTarget);

madeSensor = client.AddSensor(madeDevice, parameters).Single();
```

Where am I going wrong on this one

**Comment by lordmilko** [comment]
Hi @JamesDolphin,

Are you able to confirm whether or not the `serviceTarget` was null or not? The implication here is that this value is `null`

**Comment by JamesDolphin** [comment]
Ok in this case serviceTarget is null. I assume this means it can not find a service that contains "sensor.ServiceName"

When setting these sensors up manually all available services are showing in the PRTG ui

**Comment by lordmilko** [comment]
You might want to have a look at the services returned by `client.Targets.GetWmiServices(madeDevice)` and see whether the service you're trying to find is actually in the list, and whether you're matching against it correctly
