### ISSUE TITLE
Report for the last 2 months using the PRTGapi

### ISSUE THREAD

**Issue by MPrica12** [lordmilko/PrtgAPI#338]
### What's going on?

Hello,

I'm trying to create an export of all of the instances each sensors went down from an .xlsx file in the last 2 months

I'm not sure what the issue is but when I try to make an export from PRTG using the API and following the documentation in the Get-ObjectLog section the data being pulled in the export is only from the last 3 days, as those are the only instances when the sensors seems to have went down, which is impossible as we are sure some of those sensors went down in more times in the last 2 months. Am I configuring something wrong in my script?

$EndDate = Get-Date -Day 1 -Month 4 -Year 2023
$StartDate = Get-Date -Day 31 -Month 5 -Year 2023

$Xls = Import-Excel "C:\Monitoring_documents\Files_work\test.xlsx"

$export = foreach($line in $Xls.Id){
    Write-Host "Processing sensor " $line
    $Logs = Get-Sensor -id $line | Get-ObjectLog -StartDate $StartDate -EndDate $EndDate -Status Down
    $Logs | Select-Object DateTime, Id, Name, Status, Message 
    Write-Host "Found sensor with down status in the period with ID " $Logs.Id
    start-sleep 2
}

$export | Export-Csv C:\Monitoring_documents\Files_work\Sensors_down_FPS_updated.csv

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by MPrica12** [comment]
Hello @lordmilko,

Thanks a lot for your response, I am working on making it working by using Get-SensorHistory, but I seem to be facing issues with the DateTire format of Powershell, I keep getting this error when running the below:
$EndDate = Get-Date -Day 1 -Month 4 -Year 2023
$StartDate = Get-Date -Day 31 -Month 5 -Year 2023

$history = Get-Sensor -Id 74710 | Get-SensorHistory -Report -StartDate $StartDate -EndDate $EndDate | where Status -eq Down

Get-SensorHistory: String '4/13/2023 10:06:17 AM'(example of time) was not recognized as a valid DateTime.

I tried using ParseExact before running the command but I still get the same error:

$EndDate1 = [DateTime]::ParseExact('01/04/2023 00:00:00', 'dd/MM/yyyy HH:mm:ss', $null)
$StartDate1 = [DateTime]::ParseExact('31/05/2023 23:59:59', 'dd/MM/yyyy HH:mm:ss', $null)

$history = Get-Sensor -Id 74710 | Get-SensorHistory -Report -StartDate $StartDate1 -EndDate $EndDate1 | where Status -eq Down

Get-SensorHistory: String '4/13/2023 10:06:17 AM' was not recognized as a valid DateTime.

**Comment by lordmilko** [comment]
Hi @MPrica12,

Can you reproduce the exception with the datetime and then provide the output of `$error[0].Exception.StackTrace`

**Comment by MPrica12** [comment]
Hi @lordmilko,

Here is the output:

PS C:\Scripts\Scripts Powershell> $error[0].Exception.StackTrace
   at System.DateTime.Parse(String s)
   at PrtgAPI.PrtgClient.GetSensorHistoryReportInternal(Either`2 sensorOrId, PrtgResponse response)
   at PrtgAPI.PrtgClient.GetSensorHistoryReport(Either`2 sensorOrId, Nullable`1 startDate, Nullable`1 endDate)
   at PrtgAPI.PowerShell.Cmdlets.GetSensorHistory.<ProcessSensorHistoryReport>b__39_0()
   at PrtgAPI.PowerShell.Progress.ProgressTask`1.<>c__DisplayClass4_0`1.<Create>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at PrtgAPI.PowerShell.Progress.ProgressTask`1.ValueEmpty()
   at PrtgAPI.PowerShell.Progress.ProgressTask`1.Write()
   at PrtgAPI.PowerShell.Cmdlets.GetSensorHistory.ProcessSensorHistoryReport()
   at PrtgAPI.PowerShell.Cmdlets.GetSensorHistory.ProcessRecordEx()
   at PrtgAPI.PowerShell.Base.PrtgCmdlet.ExecuteWithCoreState(Action action)
   at System.Management.Automation.CommandProcessor.ProcessRecord()

**Comment by MPrica12** [comment]
I just tried running it without any kind of startdate or enddate parameters and I get the same error:

Get-SensorHistory: String '6/20/2023 2:01:11 PM' was not recognized as a valid DateTime.

Here is the StackTrace:

at System.DateTime.Parse(String s)
   at PrtgAPI.PrtgClient.GetSensorHistoryReportInternal(Either`2 sensorOrId, PrtgResponse response)
   at PrtgAPI.PrtgClient.GetSensorHistoryReport(Either`2 sensorOrId, Nullable`1 startDate, Nullable`1 endDate)
   at PrtgAPI.PowerShell.Cmdlets.GetSensorHistory.<ProcessSensorHistoryReport>b__39_0()
   at PrtgAPI.PowerShell.Progress.ProgressTask`1.<>c__DisplayClass4_0`1.<Create>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at PrtgAPI.PowerShell.Progress.ProgressTask`1.ValueEmpty()
   at PrtgAPI.PowerShell.Progress.ProgressTask`1.Write()
   at PrtgAPI.PowerShell.Cmdlets.GetSensorHistory.ProcessSensorHistoryReport()
   at PrtgAPI.PowerShell.Cmdlets.GetSensorHistory.ProcessRecordEx()
   at PrtgAPI.PowerShell.Base.PrtgCmdlet.ExecuteWithCoreState(Action action)
   at System.Management.Automation.CommandProcessor.ProcessRecord()

**Comment by lordmilko** [comment]
This is a bug in PrtgAPI which is occurring because the datetime format of your system is MM/dd/yyyy. You can temporarily work around this by changing your date format to be MM/dd/yyyy. I will investigate what may be required to resolve this

**Comment by MPrica12** [comment]
Hello @lordmilko 

I just did a few changes to the DateTime, now I get a different error:

**Get-SensorHistory: Failed to find the table 'table_statereporttable' in the specified HTML response.**

What do you think I should do about this?

**Comment by lordmilko** [comment]
Can you please provide the output of `Get-PrtgClient -Diagnostic`

In addition, if you execute `Get-SensorHistory -Report` with the `-Verbose` parameter it will show you the API request that was executed

```powershell
C:\> get-sensor -id 2056|Get-SensorHistory -Report -verbose
http://prtg.example.com/historicdata_html.htm?edate...
```
If you copy and paste this entire URL in your web browser it should bring up the report, with the Sensor Status History section down the bottom. If you're using Chrome, and then do Ctrl+Shift+J, you can use the Selector button to select the Sensor Status History header

![image](https://github.com/lordmilko/PrtgAPI/assets/6138789/8c2130c9-8a9b-4fa6-8ac3-35d34037057e)

![image](https://github.com/lordmilko/PrtgAPI/assets/6138789/3813b863-7b27-43de-924f-f44e2641f810)

If you then look at the adjacent HTML inside the table-wrapper div and form, you should see a table

![image](https://github.com/lordmilko/PrtgAPI/assets/6138789/52f3f2f4-643b-4623-adb4-5bdff604dcb4)

The expected name of this table is `table_statereporttable` as you can see in this screenshot. If the table doesn't exist, or has a different name, this will help explain why we're getting an error it couldn't find the table. Are you able to advise whether or not the table exists or not, and if so what its `id` is

**Comment by MPrica12** [comment]
Here is the output:

**PSVersion      : 7.3.4
PSEdition      : Core
OS             : Microsoft Windows 10.0.19041
PrtgAPIVersion : 0.9.18
Culture        : ro-RO
CLRVersion     : .NETCoreApp,Version=v7.0
PrtgVersion    : 23.2.83.1760
PrtgLanguage   : english.lng**

I will look into the table_statereporttable and will provide it soon, thank you!
