### ISSUE TITLE
Get-Sensor hexadecimal value 0x00

### ISSUE THREAD

**Issue by isabelleriedl** [lordmilko/PrtgAPI#55]
Tried to get all sensors:
get-sensor : '.', hexadecimal value 0x00, is an invalid character. Line 11551, position 26.
At line:1 char:12
+ $sensors = get-sensor
+            ~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-Sensor], XmlException
    + FullyQualifiedErrorId : System.Xml.XmlException,PrtgAPI.PowerShell.Cmdlets.GetSensor

**Comment by isabelleriedl** [comment]
Hi!

Thanks for your response!

Here is the output:

PS C:\Windows\system32> $error[0].Exception.StackTrace
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlReader.SetupReadElementContentAsXxx(String methodName)
   at System.Xml.XmlReader.ReadElementContentAsString()
   at ReadSensor(Closure , XmlExpressionSerializerImpl , XmlReader , Boolean )
   at ReadTableData`1(Closure , XmlExpressionSerializerImpl , XmlReader , Boolean )
   at ReadTableData`1Outer(Closure , XmlExpressionSerializerImpl , XmlReader , Boolean )
   at PrtgAPI.Request.ObjectEngine.GetObjectsRaw[T](IXmlParameters parameters, Action`1 responseValidator, Func`2 respon
seParser, Boolean validateValueTypes, CancellationToken token)
   at PrtgAPI.PowerShell.Base.PrtgTableCmdlet`2.PrtgAPI.PowerShell.Base.IStreamableCmdlet<PrtgAPI.PowerShell.Base.PrtgTa
bleCmdlet<TObject,TParam>,TObject,TParam>.GetStreamObjects(TParam parameters)
   at PrtgAPI.Request.ObjectEngine.<SerialStreamObjectsInternal>d__21`2.MoveNext()
   at PrtgAPI.PowerShell.Base.PrtgProgressCmdlet.WriteList[T](IEnumerable`1 sendToPipeline)
   at PrtgAPI.PowerShell.Base.PrtgCmdlet.ExecuteWithCoreState(Action action)
   at System.Management.Automation.CommandProcessor.ProcessRecord()


BTW, Get-Object doesn’t throw any error.

Kind Regards

Von: lordmilko <notifications@github.com>
Gesendet: Donnerstag, 10. Januar 2019 21:30
An: lordmilko/PrtgAPI <PrtgAPI@noreply.github.com>
Cc: Riedl Isabelle <Isabelle.Riedl@acp.at>; Mention <mention@noreply.github.com>
Betreff: Re: [lordmilko/PrtgAPI] Get-Sensor hexadecimal value 0x00 (#55)


Hi @isabelleriedl<https://github.com/isabelleriedl>,

Can I get you to type Get-Sensor, then type $error[0].Exception.StackTrace and copy the output here?

**Comment by isabelleriedl** [comment]
Thank you very much!
It is working with 0.9.1!

And thank you for this great module! ☺

Kind regards!
Isi

Von: lordmilko <notifications@github.com>
Gesendet: Freitag, 11. Januar 2019 08:26
An: lordmilko/PrtgAPI <PrtgAPI@noreply.github.com>
Cc: Riedl Isabelle <Isabelle.Riedl@acp.at>; Mention <mention@noreply.github.com>
Betreff: Re: [lordmilko/PrtgAPI] Get-Sensor hexadecimal value 0x00 (#55)


Thanks @isabelleriedl<https://github.com/isabelleriedl>,

This issue was caused by a change made in PrtgAPI 0.9.2. I am currently working on putting together a solution for this and will hopefully release PrtgAPI 0.9.5 in the next couple of days

In the meantime, you can potentially work around this issue by downgrading to PrtgAPI 0.9.1.

To do this, close all open PowerShell windows, then open a new one and do

Uninstall-Module PrtgAPI -AllVersions

Install-Module -Name PrtgAPI -RequiredVersion 0.9.1

If you then do

ipmo PrtgAPI

gmo PrtgAPI

It should show you are using PrtgAPI 0.9.1

Regards,
lordmilko

**Comment by lordmilko** [comment]
Hi @isabelleriedl,

PrtgAPI 0.9.5 has now been released, which should contain a fix for this issue

To update PrtgAPI, simply run

```powershell
Update-Module PrtgAPI
```

then reopen PowerShell

Please let me know if you have any issues

Regards,
lordmilko
